version: '2.0'
services:
    web:
      build: .
      env_file: .env
      environment:
        - REDIS=http://redis
      ports:
        - "8080:8080"
      links:
        - redis
    redis:
      image: redis